baseURL: "https://brendantang.net"
languageCode: "en-us"
title: "brendan tang"
paginate: 20
enableGitInfo: true
ignoreErrors: 
  - error-remote-getjson

permalinks:
  posts: /:year/:month/:title/
  notes: /:year/:month/:title/

params:
  mainSections:
    - posts
